services:
#    aacp_online_convert_api.example:
#        class: Aacp\OnlineConvertApiBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    oc.information:
        class: Aacp\OnlineConvertApiBundle\Handler\Information
        arguments: [ "@sdk.information", %oc.api_key%, %oc.decorator% ]

    oc.all_conversions:
        class: Aacp\OnlineConvertApiBundle\Handler\Conversion
        arguments: [ "@sdk.job.creator" ]

    oc.base_conversion:
        class: Aacp\OnlineConvertApiBundle\Handler\BaseConversion
        arguments: [ "@sdk.job.creator" ]

    sdk.information:
        class: Qaamgo\InformationApi
        public: false

    sdk.job.creator:
        class: Qaamgo\JobCreator
        arguments: [ false, null, %oc.api_key% ]
        public: false

    oc.listener.request:
        class: Aacp\OnlineConvertApiBundle\EventListener\OnlineConvertRequest
        tags:
            - { name: kernel.event_listener, event: kernel.request }