services:
    oc.information:
        class: Aacp\OnlineConvertApiBundle\Handler\Information
        arguments: [ "@sdk.information", %oc.api_key% ]

    oc.conversion.factory:
        class: Aacp\OnlineConvertApiBundle\Handler\Conversion\Factory
        arguments: [ "@sdk.job.sync.creator", "@sdk.job.async.creator", "@oc.routing.callback.loader", "%oc.host%" ]

    oc.routing.callback.loader:
        class: Aacp\OnlineConvertApiBundle\Routing\CallbackLoader
        tags:
            - { name: routing.loader }

    sdk.client:
        class: Qaamgo\ApiClient
        arguments: [ %oc.https% ]

    sdk.information:
        class: Qaamgo\InformationApi
        arguments: ["@sdk.client"]
        public: false

    sdk.job.sync.creator:
        class: Qaamgo\Job\Sync
        arguments: [ "@sdk.client", "@sdk.information", %oc.api_key% ]
        public: false
    sdk.job.async.creator:
            class: Qaamgo\Job\Async
            arguments: [ "@sdk.client", "@sdk.information", %oc.api_key% ]
            public: false

    oc.listener.request:
        class: Aacp\OnlineConvertApiBundle\EventListener\OnlineConvertRequest
        tags:
            - { name: kernel.event_listener, event: kernel.request }